version: "3.9"

services:
  llm_meetup:
    build: .
    image: llm-meetup
    container_name: llm_meetup
    command: ["llm_proxy.py", "-H", "${LLM_PROXY_HOST}", "-p", "${LLM_PROXY_PORT}"]
    ports:
      - "${LLM_PROXY_PORT}:${LLM_PROXY_PORT}"
    volumes:
      - ./config:/app/config
      - ./personas:/app/personas
      - ./logs:/app/logs
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.llm_meetup.rule=HostSNI(`${TRAFFIC_DOMAIN}`)"
      - "traefik.tcp.routers.llm_meetup.entrypoints=llm-meetup"
      - "traefik.tcp.services.llm_meetup.loadbalancer.server.port=${LLM_PROXY_PORT}"
      - "traefik.docker.network=traefik_public"

networks:
  traefik_public:
    external: true
