# OpenAI Configuration

# Model selection
model: gpt-4o-mini
# Available models:
# model: gpt-4o
# model: gpt-4-turbo-preview
# - gpt-4-turbo-preview (most capable, latest model)
# - gpt-4-0125-preview
# - gpt-4-1106-preview
# - gpt-4-vision-preview (for image analysis)
# - gpt-4 (8K context)
# - gpt-4-32k (32K context)
# - gpt-3.5-turbo (most up to date GPT-3.5 model)
# - gpt-3.5-turbo-16k (16K context)
# - gpt-3.5-turbo-1106 (updated GPT-3.5 model)
# - gpt-3.5-turbo-0125 (latest GPT-3.5 model, as of Feb 2024)

max_tokens: 4096
temperature: 0.7
system_prompt: "You are a helpful AI assistant."

# Additional optional parameters
# top_p: 1.0
# frequency_penalty: 0.0
# presence_penalty: 0.0
# stop: ["\n", " Human:", " AI:"]

# API configuration (if using a different endpoint)
# api_type: "azure"
# api_base: "https://your-azure-openai-resource.openai.azure.com/"
# api_version: "2023-05-15"

# Deployment ID (for Azure OpenAI)
# engine: "deployment-name"